# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import qall.provider.worker.protobuf.qc_worker_api_v1.qc_worker_api_v1_pb2 as qc__worker__api__v1__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in qc_worker_api_v1_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateContext = channel.unary_unary(
            "/qc_worker_api_v1.Api/CreateContext",
            request_serializer=qc__worker__api__v1__pb2.CreateContextRequest.SerializeToString,
            response_deserializer=qc__worker__api__v1__pb2.QuantumContext.FromString,
            _registered_method=True,
        )
        self.Run = channel.unary_unary(
            "/qc_worker_api_v1.Api/Run",
            request_serializer=qc__worker__api__v1__pb2.RunRequest.SerializeToString,
            response_deserializer=qc__worker__api__v1__pb2.RunResponse.FromString,
            _registered_method=True,
        )
        self.CloseContext = channel.unary_unary(
            "/qc_worker_api_v1.Api/CloseContext",
            request_serializer=qc__worker__api__v1__pb2.CloseContextRequest.SerializeToString,
            response_deserializer=qc__worker__api__v1__pb2.QuantumContext.FromString,
            _registered_method=True,
        )
        self.GetCapabilities = channel.unary_unary(
            "/qc_worker_api_v1.Api/GetCapabilities",
            request_serializer=qc__worker__api__v1__pb2.GetCapabilitiesRequest.SerializeToString,
            response_deserializer=qc__worker__api__v1__pb2.Capabilities.FromString,
            _registered_method=True,
        )


class ApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateContext(self, request, context):
        """Initialize a quantum execution context."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Run(self, request, context):
        """Execute a quantum program."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseContext(self, request, context):
        """Close an execution context and release associated resources."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetCapabilities(self, request, context):
        """Optional health/capability discovery."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateContext": grpc.unary_unary_rpc_method_handler(
            servicer.CreateContext,
            request_deserializer=qc__worker__api__v1__pb2.CreateContextRequest.FromString,
            response_serializer=qc__worker__api__v1__pb2.QuantumContext.SerializeToString,
        ),
        "Run": grpc.unary_unary_rpc_method_handler(
            servicer.Run,
            request_deserializer=qc__worker__api__v1__pb2.RunRequest.FromString,
            response_serializer=qc__worker__api__v1__pb2.RunResponse.SerializeToString,
        ),
        "CloseContext": grpc.unary_unary_rpc_method_handler(
            servicer.CloseContext,
            request_deserializer=qc__worker__api__v1__pb2.CloseContextRequest.FromString,
            response_serializer=qc__worker__api__v1__pb2.QuantumContext.SerializeToString,
        ),
        "GetCapabilities": grpc.unary_unary_rpc_method_handler(
            servicer.GetCapabilities,
            request_deserializer=qc__worker__api__v1__pb2.GetCapabilitiesRequest.FromString,
            response_serializer=qc__worker__api__v1__pb2.Capabilities.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "qc_worker_api_v1.Api", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("qc_worker_api_v1.Api", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qc_worker_api_v1.Api/CreateContext",
            qc__worker__api__v1__pb2.CreateContextRequest.SerializeToString,
            qc__worker__api__v1__pb2.QuantumContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Run(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qc_worker_api_v1.Api/Run",
            qc__worker__api__v1__pb2.RunRequest.SerializeToString,
            qc__worker__api__v1__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloseContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qc_worker_api_v1.Api/CloseContext",
            qc__worker__api__v1__pb2.CloseContextRequest.SerializeToString,
            qc__worker__api__v1__pb2.QuantumContext.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetCapabilities(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qc_worker_api_v1.Api/GetCapabilities",
            qc__worker__api__v1__pb2.GetCapabilitiesRequest.SerializeToString,
            qc__worker__api__v1__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
